### ISSUE TITLE
Authentication Fails in NW.js export

### ISSUE THREAD

**Issue by BrandyBuizel** [sotano42/rex_ngio_authentication_C3_port#1] opened 2020-07-10 17:02 UTC
Works properly on HTML5 but when exporting for desktop platforms using NW.js there's an error in the console about not getting a valid session.

"newgroundsio.min.js:227 Attempted to open Newgrounds Passport without a valid passport_url. Be sure you have called getValidSession() first!."

**Comment by sotano42** [comment] 2020-07-10 17:36
Hey! This issue is because ng api is meant for html5 games only, not for any other export, and it tries to authenticate on its portal opening a session through a popup window. I'm sorry but I can't help you on this since is a tech restriction. You should consider using cloud services of any other platform.

**Comment by BrandyBuizel** [comment] 2020-07-10 18:08
I'm aware, but I'd like to add a little extra integration for NG users. If the browser plugin can open tabs to do this in NW.js then surely there shouldn't be an issue for this plugin to access the default browser.

**Comment by sotano42** [comment] 2020-07-10 19:14
This has nothing to do with the plugin, what tries to sign in is the ng api script. I can't modify the api because: 1 that's how it works, 2. Is minified, 3. Is only meant for web browser games.

You should definitively consider firebase or playfab for any cloud data integration, leaderboards or saved games.

**Comment by PsychoGoldfishNG** [comment] 2020-07-10 20:26
Just want to clarify that NGIO is NOT intended just for web games.  Anything that can make http requests and load some kind of browser context should be able to sign in to NG Passport.

The NG portal makes this process simple by pre-generating sessions and passing them to html5 web games via the URI, but you can also use App.startSession to create a new session and App.checkSession to validate a session once you've loaded it.

Check out http://www.newgrounds.io/help/passport/ for details on how this could be implemented.

**Comment by sotano42** [comment] 2020-07-11 01:29
@PsychoGoldfishNG Well, the part of code that's failing according to @BrandyBuizel is the javascript API, and that's the official JS API by NG.

@BrandyBuizel please provide a minimum c3p project file that reproduces the error to see if there's any workaround. I can't guarantee it works because the javascript API that the plugin uses is minified, and the documentation says nothing about compatibility with NWJS, but I can try to take a second look. Nevertheless, the steps for implementing the API are followed correctly, and it is important to highlight that ** I didn't write the original NG plugin, I did modify it to be able to run it in Construct 3 **, the original plugin is open source and was written by rexrainbow, that's why I made this repository public. Feel free to contribute.

**Comment by BrandyBuizel** [comment] 2020-07-11 21:03
[New project.zip](https://github.com/sotano42/rex_ngio_authentication_C3_port/files/4907590/New.project.zip)

Here's a blank .c3p i added authentication to, got the same error with minimal variables trying to sign into the API. Works in HTML5, fails a step in the NW.js export. **Click the button to login, several checks if successful including the icon changing color to orange**

**Comment by sotano42** [comment] 2020-07-19 09:18
@BrandyBuizel I did review your sample project, first thing I noticed is you had Worker mode in auto, this plugin works only with worker mode off. I also made some exports, and I can confirm that the problem is not within the plugin, since it follows the steps NG requires for a login, so I will close the issue because of this reason.

Now I've found several network errors on the Devtools of chromium, the possibilities can be:
- NG is blocking the request (probably)
- You may need to whitelist the URL of NG api, (https://newgrounds.io/gateway_v3.php) but this seems more unlikely to be true since I did some testing to call it from the DevTools of NW.js and I got a response, which means the URL is reachable. I even did some testing with the AJAX plugin and the URL can be reached to and responds, although with an error due to incomplete information since I just called raw (url).
- The error is thrown within the newgroundsio.min.js, if it is a bug the you'll need to contact newgrounds so that they can take a look at the problem. This is an old way of calling services, they created a PHP endpoint and communicate with it with a form within the HTML, which is valid but outdated compared with the current REST services available on other ends.

![image](https://user-images.githubusercontent.com/10860045/87871097-599b6680-c973-11ea-9bac-16b52a283f3d.png)

I still recommend you try more reliable cloud services like firebase, playfab or azure as they offer better solutions than NG API.

**Closed as completed by sotano42** 2020-07-19 09:18 UTC
